### ISSUE TITLE
 Cannot convert a null value to an object of type Dependency

### ISSUE THREAD

**Issue by DeepCoreB4** [nicegram/Nicegram-Android#5]
This line in the build.gradle gives me an error `implementation (properties.getProperty("assistant.aar")) { transitive = true }`

error:
`...\Nicegram-Android-main\nicegram-features\build.gradle'` line: 77
`A problem occurred evaluating project ':nicegram-features'.
> Cannot convert a null value to an object of type Dependency.
  The following types/formats are supported:
    - Instances of Dependency..
    -...
    -...
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.`

and if i comment this line out
`...\Nicegram-Android-main\nicegram-features\build.gradle' line: 77`

  i got this error:
> You must specify a URL for a Maven repository.

Where is the 
```
(properties.getProperty("assistant.aar")) 
``` 
file located? Can't finde anywhere in the projectStructure.
[I tried the original Repo ](https://github.com/DrKLO/Telegram)
and everything works fine. without the nicegram-features.

Is there any Fix...or suggestions how to compile propely right?
Thx for repy...

Peace

**Comment by denis-zhuravlev** [comment]
Hi, @DeepCoreB4. Our Nicegram Assistant module is not open source by now, so you can't build Nicegram app from this source. But this repo can help you to inspect all the changes we've made to Telegram source code.
